import { TfaProvider } from 'src/core/Gigya.Js/app/TFA/types';
import { FormInput } from 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Inputs/FormInput';
import { BaseTfaRegistrationWidget } from '../BaseTfaRegistrationWidget';
export declare class TfaRegistrationPhoneWidget extends BaseTfaRegistrationWidget {
    static CONSTS: {
        selector: string;
        continueButtonSelector: string;
        resendButtonSelector: string;
        chooseMethodSelector: string;
        chooseMethodOptionName: string;
        currentStepAttribute: string;
        voiceAllowedAttribute: string;
        phoneNumberPreviewSelector: string;
        sendCodeStepSelector: string;
        verifyStepSelector: string;
        rememberDeviceSelector: string;
        hiddenClass: string;
        phoneFieldName: string;
        deps: (typeof FormInput)[];
    };
    protected readonly providerName = TfaProvider.phone;
    private phvToken;
    private resendPhoneLink;
    linkInstanceElement(parent: HTMLElement): Promise<void>;
    unlinkInstanceElement(): void;
    private init;
    private showSendCodeStep;
    private showVerifyStep;
    private addEventHandlers;
    private submitPhoneNumber;
    private sendCode;
    private submitCode;
    private get sendCodeButton();
    private get verificationButton();
    private get resendButton();
    private set widgetState(value);
    private get hasVoiceCapability();
    private get chooseMethodEl();
    private get sendVerificationStepEl();
    private get sendCodeStepEl();
    private get selectedMethod();
    private get currentCode();
    private get hostForm();
    private get phoneNumber();
    private get previewEl();
    private get phoneNumberFormField();
    protected get rememberDevice(): boolean;
    private get rememberDeviceCheckboxEl();
    private get codeFormField();
    private get phoneNumberFieldName();
}
