import { TranslatedWidget } from './TranslatedWidget';
import { IFormResponse } from '../ScreenSetPlugin';
import { IValidationInfo } from '../Inputs/FormInput';
import { BaseFormWidget } from '../BaseFormWidget';
export declare const PhoneNumberWidget_CONSTS: {
    selector: string;
    verifyButtonClass: string;
    resendButtonCLass: string;
    phonePreviewClass: string;
    useAsIdentifierAttr: string;
    codeInputClass: string;
    phoneInputNumberClass: string;
    countryCodeInputClass: string;
    verifiedStatusClass: string;
    resendBlockedLabelClass: string;
    linkDisabledClass: string;
    errorMessageClass: string;
    placeholderTextAttribute: string;
    gigyaHiddenClass: string;
    placeholderAttribute: string;
    widgetStateAttribute: string;
    requiredAttribute: string;
    codeStateAttributes: string;
    displayNameAttribute: string;
    translationKeyAttribute: string;
    resendBlockDefaultLabelAttr: string;
    phoneNumberFieldName: string;
    resendCountTemplate: string;
    disableVerifyInSeconds: number;
    otpCodeLength: number;
    deps: (typeof TranslatedWidget)[];
};
export declare class PhoneNumberWidget extends BaseFormWidget<HTMLDivElement> {
    static readonly CONSTS: {
        selector: string;
        verifyButtonClass: string;
        resendButtonCLass: string;
        phonePreviewClass: string;
        useAsIdentifierAttr: string;
        codeInputClass: string;
        phoneInputNumberClass: string;
        countryCodeInputClass: string;
        verifiedStatusClass: string;
        resendBlockedLabelClass: string;
        linkDisabledClass: string;
        errorMessageClass: string;
        placeholderTextAttribute: string;
        gigyaHiddenClass: string;
        placeholderAttribute: string;
        widgetStateAttribute: string;
        requiredAttribute: string;
        codeStateAttributes: string;
        displayNameAttribute: string;
        translationKeyAttribute: string;
        resendBlockDefaultLabelAttr: string;
        phoneNumberFieldName: string;
        resendCountTemplate: string;
        disableVerifyInSeconds: number;
        otpCodeLength: number;
        deps: (typeof TranslatedWidget)[];
    };
    private readonly debounceDelay;
    private resendTimeoutId;
    private vToken;
    private errorDisplayEl;
    linkInstanceElement(parent: HTMLElement): void;
    unlinkInstanceElement(): void;
    renderWidget(): void;
    validateAsync(): Promise<IValidationInfo>;
    isRequired(): boolean;
    private init;
    private startFlow;
    private hideVerifiedMessage;
    private get isIdentifierMode();
    private showPhoneNumberStep;
    private showVerificationStep;
    private showVerificationState;
    private showPhoneVerified;
    private showExistingPhoneNumber;
    private switchToState;
    private onCodeSent;
    private startResendCountDown;
    private changeResendBlockedMessage;
    private getCountDownText;
    private disableResend;
    private enableResendCode;
    private onPhoneInputChange;
    private toggleVerify;
    private enableVerifyButton;
    private disableVerifyButton;
    private onCodeInputChange;
    private resendCodeHandler;
    private verifyButtonClickHandler;
    private disableVerifyScreen;
    private enableVerifyScreen;
    private setVToken;
    private otpUpdate;
    private otpSendCode;
    private displayError;
    private showErrorMessage;
    private hideErrorMessage;
    protected getErrorKeyFromResponse(response: IFormResponse): string;
    private enableCodeInput;
    private disableCodeInput;
    private get accountPhoneNumber();
    private get verifyButtonEl();
    private get resendButtonEl();
    private get phonePreviewEl();
    private get codeInputEl();
    private get phoneInputEl();
    private get countryCodeEl();
    private get phoneNumber();
    private get phoneNumberMasked();
    private get phoneNumberWithoutCode();
    private isCurrentState;
    private get countryCode();
    private get codePlaceholder();
    private get errorMessageEl();
    private get verifiedFormNumber();
    private get verifiedPhoneNumberField();
    private get resendBlockedEl();
    private get resendCountDownTranslationKey();
    private get resendCountdownDefaultLabel();
    private get requiredErrorKey();
}
