import * as Screen from 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Screen';
import * as ScreenConsts from 'src/accounts/Gigya.JS.Plugin.screenSet2/app/ScreenConsts';
import * as ScreenOptions from 'src/accounts/Gigya.JS.Plugin.screenSet2/app/ScreenOptions';
import * as ScreenSetData from 'src/accounts/Gigya.JS.Plugin.screenSet2/app/ScreenSetData';
import * as ScreenSetPlugin from 'src/accounts/Gigya.JS.Plugin.screenSet2/app/ScreenSetPlugin';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Forms/OtpSendCodeForm';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Forms/OtpUpdateForm';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Forms/OtpVerifyForm';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Forms/OtpLoginForm';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Widgets/ApiLinkWidget';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Forms/LinkAccountsForm';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Captcha';
import 'src/accounts/Gigya.JS.Plugin.screenSet2/app/Handlers';
export * from './Forms';
export * from './Widgets';
export * from './Handlers';
export * as utils from 'src/accounts/Gigya.JS.Plugin.screenSet2/app/utils';
export * from './Inputs';
export * from './DataProviders';
export * from './elements';
export { Screen, ScreenConsts, ScreenOptions, ScreenSetData, ScreenSetPlugin, };
declare const _default: ScreenSetPlugin.ScreenSetPlugin;
export default _default;
