import { IModalDialogParams } from 'src/core/Gigya.Js.Plugin/app/interfaces/IModalDialogParams';
import { LoadDimmer } from 'src/core/Gigya.Js.Plugin/app/helpers/LoadDimmer';
import { IBaseObjectConfig } from 'src/core/Gigya.Js/app/BaseObject/IBaseObjectConfig';
import { IElementSize } from 'src/core/Gigya.Js/app/Interfaces';
declare const BaseObjectGlobal: any;
export declare class ModalDialog extends BaseObjectGlobal<IModalDialogParams> {
    private _triggerMethod;
    isMobileUI: any;
    isLegacy: boolean;
    private _dialogClasses;
    private _allContainer;
    private _mainContainer;
    private _captionContainer;
    private _contentContainer;
    private _closeButtonElement;
    private _loader;
    private onWindowResizeEvent;
    onAfterCenterEvent(): gigya._.EventWrapper<() => void>;
    constructor(_triggerMethod: string, isMobileUI: any, params: IModalDialogParams, isLegacy?: boolean, hide?: boolean);
    getConfig(): IBaseObjectConfig<IModalDialogParams>;
    showAll(): void;
    hideAll(): void;
    showMainDialog(): void;
    hideMainDialog(): void;
    showLoading(): void;
    hideLoading(): void;
    changeToMobile(): void;
    changeToWeb(): void;
    isLoading(): boolean;
    resize(size: IElementSize): void;
    private applyStyle;
    private addWindowResizeListener;
    private removeWindowResizeListener;
    private onWindowResize;
    private adjustWindowHeight;
    center(): void;
    private create;
    getMainContainer(): HTMLElement;
    getContentContainer(): HTMLElement;
    getCaptionContainer(): HTMLElement;
    getModalDialogContainer(): HTMLElement;
    getLoadingIndicator(): LoadDimmer;
    dispose(): void;
}
export {};
