import { TFAVerificationBaseItemWidget } from '../TFAVerificationBaseItemWidget';
import { ITfaPhoneItem, TfaPhoneSendCodeMethod, TfaProvider } from 'src/core/Gigya.Js/app/TFA/types';
import { FormInput } from '../../../../Inputs/FormInput';
import { BaseForm } from '../../../../BaseForm';
export declare const TFAPhoneItem_CONSTS: {
    selector: string;
    codeInputSelector: string;
    sendSMSButtonSelector: string;
    sendVoiceButtonSelector: string;
    resendButtonSelectorSms: string;
    resendButtonSelectorVoice: string;
    countDownSelector: string;
    gigyaHiddenClass: string;
    sendButtonSelector: string;
    submitButtonSelector: string;
    resendButtonSelector: string;
    expandedAttribute: string;
    errorMessageSelector: string;
    errorActiveMessageClass: string;
    rememberDeviceSelector: string;
    symbolsPlaceholder: string;
    nameAttr: string;
    boundToAttr: string;
    inputErrorSelector: string;
    ariaLabelAttr: string;
    containerClass: string;
    containerEnabledClass: string;
};
export declare class TFAVerificationPhoneItemWidget extends TFAVerificationBaseItemWidget {
    private _domUtils;
    static CONSTS: {
        selector: string;
        codeInputSelector: string;
        sendSMSButtonSelector: string;
        sendVoiceButtonSelector: string;
        resendButtonSelectorSms: string;
        resendButtonSelectorVoice: string;
        countDownSelector: string;
        gigyaHiddenClass: string;
        sendButtonSelector: string;
        submitButtonSelector: string;
        resendButtonSelector: string;
        expandedAttribute: string;
        errorMessageSelector: string;
        errorActiveMessageClass: string;
        rememberDeviceSelector: string;
        symbolsPlaceholder: string;
        nameAttr: string;
        boundToAttr: string;
        inputErrorSelector: string;
        ariaLabelAttr: string;
        containerClass: string;
        containerEnabledClass: string;
    };
    protected readonly providerName = TfaProvider.phone;
    protected countdownHelper: any;
    constructor(_form: BaseForm, el: HTMLLIElement, _domUtils?: typeof gigya.utils.DOM);
    unlinkInstanceElement(): void;
    protected sendCode(params?: {
        method: TfaPhoneSendCodeMethod;
    }): Promise<void>;
    protected sendCodeApi(params?: {
        method: TfaPhoneSendCodeMethod;
    }): Promise<import("gigya").GigyaResponse>;
    protected addActionButtonEventHandlers(): void;
    protected addResendButtonHandlers(): void;
    protected onSendButtonClicked(method: TfaPhoneSendCodeMethod): Promise<void>;
    protected onResendButtonClick(method: TfaPhoneSendCodeMethod): Promise<void>;
    protected automaticallyActivateDevice(): Promise<void>;
    protected startCountDown(): Promise<void>;
    protected verifyCodeApi(): Promise<import("gigya").GigyaResponse>;
    protected get codeInput(): HTMLInputElement;
    protected get phone(): ITfaPhoneItem;
    protected get lastSymbols(): string;
    protected get codeFormField(): FormInput;
    protected get sendSmsButton(): Element;
    protected get sendVoiceButton(): Element;
    protected get resendButtons(): Element[];
    protected get resendSmsButton(): Element;
    protected get resendVoiceButton(): Element;
    protected get countDownEl(): HTMLElement;
}
