import 'src/core/Gigya.Js/app/GigyaGlobals';
import 'src/core/Gigya.Js/app/Flow/activities/ActivityLibrary';
import 'src/core/Gigya.Js/app/Flow/activities/EventActivity';
import 'src/core/Gigya.Js/app/Flow/activities/ScreenSetActivity';
import 'src/core/Gigya.Js/app/Flow/activities/InitActivity';
import 'src/core/Gigya.Js/app/Utils';
import 'src/core/Gigya.Js/app/Bootstrap';
import 'src/core/Gigya.Js/app/Prototypes';
import 'src/core/Gigya.Js/app/Logger/main';
declare const gigya: any;
export default gigya;
