import { IPlugin, IInjectionInfo } from 'src/core/Gigya.Js/app/API/UiApi';
import { IPluginParams } from 'src/core/Gigya.Js.Plugin/app/interfaces/IPluginParams';
import { IPluginTemplates } from 'src/core/Gigya.Js.Plugin/app/interfaces/IPluginTemplates';
import { IPluginCSS } from 'src/core/Gigya.Js.Plugin/app/interfaces/IPluginCSS';
import { ModalDialog } from 'src/core/Gigya.Js.Plugin/app/helpers/ModalDialog';
import { PluginStyle } from 'src/core/Gigya.Js.Plugin/app/PluginStyles';
import { LoadDimmer } from 'src/core/Gigya.Js.Plugin/app/helpers/LoadDimmer';
import { IPluginConfig } from 'src/core/Gigya.Js.Plugin/app/interfaces/IPluginConfig';
import { Poller } from 'src/core/Gigya.Js.Plugin/app/helpers/Poller';
import { GSErrors } from '../../Gigya.Js/app/GSErrors';
export declare const cssFlags: {
    [pluginName: string]: Object;
};
export declare class BasePlugin<P extends IPluginParams, HT extends IPluginTemplates, CT extends IPluginCSS> extends gigya._.BaseObject<IPluginParams> implements IPlugin {
    params: P;
    explicitParams: P;
    injectionInfo: IInjectionInfo;
    containerID: string;
    container: HTMLElement;
    static globalPixelRatio: number;
    static globalImgBase: string;
    protected _pixelRatio: number;
    protected _imgBase: string;
    protected _imgExt: string;
    private _templates;
    private _css;
    protected _modalDialog: ModalDialog;
    protected _captionElement: HTMLElement;
    isModal: boolean;
    protected MOBILE_MODAL_MIN_WIDTH: number;
    isRtl: boolean;
    isMobileUI: boolean;
    private addedCss;
    lang: string;
    protected _style: PluginStyle;
    protected _loadingIndicator: LoadDimmer;
    protected config: IPluginConfig<P>;
    localizedJsName: string;
    protected _poller: Poller;
    protected POLL_INTERVAL: number;
    onRefreshExternalComponentsEvent(): gigya._.EventWrapper<() => void>;
    protected refreshExternalComponents(): void;
    constructor(params: P, explicitParams: P, injectionInfo: IInjectionInfo);
    private getTranslationJsName;
    start(): void;
    private initUI;
    private loadComplete;
    protected initContainer(): void;
    protected initModalContainer(): void;
    protected addMetaDataClasses(topElement: HTMLElement): void;
    getPluginStyle(): PluginStyle;
    private setContainerMinSize;
    private createModalDialog;
    private injectCss;
    protected init(loadedCallback: (isSucceed?: boolean) => void): void;
    protected resizePlugin(old: gigya.IElementActualSize, curr: gigya.IElementActualSize): void;
    protected onViewportSizeChanged(old: gigya.IViewportSize, curr: gigya.IViewportSize): void;
    protected shouldClose(): boolean;
    centerModal(): void;
    resizeModal(size: gigya.IElementSize): void;
    getPhotoFullName(photoName: string, pixelRatio?: number, ext?: string, imgBase?: string): string;
    protected dispatchPluginEvent(name: string, eventObj?: Object): any;
    getTemplates(): HT;
    getCss(): CT;
    protected addCssIfDidntLoad(cssName: string, defaultCss: IPluginCSS, loadingFlags: Object, currentCss: string): string;
    getText(key: string, replaceStr?: string, withStr?: string): string;
    toString(): string;
    protected error(msg: string, errorCode?: GSErrors, e?: any): any;
    protected close(reason?: string, eventObj?: any): void;
    dispose(): void;
}
