import { PagesPlugin } from 'src/accounts/Gigya.Js.Plugin.Pages/app/PagesPlugin';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/GenericPage';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/SiteLoginPage';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/SSOLoginPage';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/SAMLLoginPage';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/OIDCLoginPage';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/ProfileUpdatePage';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/ResetPasswordPage';
import 'src/accounts/Gigya.Js.Plugin.Pages/app/pages/DeviceRegistrationPage';
export { IPagesParams, IPage } from './PagesPlugin';
export { PageType } from './types/consts';
export { GenericPage, SiteLoginPage, SSOLoginPage, SAMLLoginPage, OIDCLoginPage, ProfileUpdatePage, ResetPasswordPage, DeviceRegistrationPage, RequireSessionPage, BasePage } from './pages';
export declare const pages: () => PagesPlugin;
export default PagesPlugin;
